buildscript {
    repositories {
        mavenCentral()
    }
}

plugins {
    id 'org.sonarqube' version '3.4.0.2513'
}

apply plugin: 'idea'
apply plugin: 'java'
apply plugin: 'application'
apply plugin: 'jacoco'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'com.sun.mail:jakarta.mail:2.0.1'
    implementation 'com.sun.mail:imap:2.0.1'

    implementation 'commons-cli:commons-cli:1.4'
    implementation 'org.apache.commons:commons-lang3:3.14.0'

    implementation 'com.h2database:h2:1.4.200'

    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.2'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher:1.10.2'
    testImplementation 'org.mockito:mockito-core:5.20.0'
    testImplementation 'org.hamcrest:hamcrest:2.2'
}

group = 'com.marcnuri'
version = '0.0.1-SNAPSHOT'
java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

application {
    mainClass = 'com.marcnuri.mnimapsync.MNIMAPSync'
}

test {
    testLogging {
        exceptionFormat = 'full'
    }
    useJUnitPlatform()
    finalizedBy jacocoTestReport
}

jacocoTestReport {
    reports {
        xml.required = true
        html.required = true
    }
}

task fatJar(type: Jar, group: BasePlugin.BUILD_GROUP) {
    manifest {
        attributes (
            'Main-Class': application.mainClass.get(),
            'Class-Path': configurations.runtimeClasspath.files.collect { "$it.name" }.join(' ')
        )
    }
    archiveBaseName = project.name
    archiveVersion = ''
    archiveClassifier = 'all'
    from { configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) } }
    with jar
}
